import fs from 'node:fs';
import path from 'node:path';
import { markArtifactStatus } from '../artifacts.js';
import {
  BACKEND_CONTRACT_SECTIONS,
  BACKEND_RULES,
  backendAvailabilityFromDna,
} from './backendContract.js';
import { loadDna } from './dna.js';

function readContract(artifactsDir) {
  const p = path.join(artifactsDir, 'feature-contract.md');
  if (!fs.existsSync(p)) return '';
  return fs.readFileSync(p, 'utf8');
}

export function scaffoldBackendDependency(root, artifactsDir, runId) {
  const dna = loadDna(root);
  const availability = dna ? backendAvailabilityFromDna(dna) : 'unknown';
  const contract = readContract(artifactsDir);
  const needsBackend = /api|endpoint|backend|server|payload|response/i.test(contract);

  const p = path.join(artifactsDir, 'backend-dependency.md');
  let content = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';

  content = content.replace(
    /\*\*Backend availability:\*\* yes \| no \| unknown/,
    `**Backend availability:** ${availability}`
  );

  if (!content.includes('## Scaffold notes')) {
    content += `\n\n## Scaffold notes

- Generated by \`eos intel backend\`
- Sections tracked: ${BACKEND_CONTRACT_SECTIONS.join(', ')}
- Needs backend per contract heuristics: ${needsBackend ? 'yes' : 'unclear — verify manually'}

### Rules applied

${BACKEND_RULES.map((r) => `- ${r}`).join('\n')}
`;
  }

  if (availability === 'unknown' && !content.includes('### Human follow-ups required')) {
    content += `\n\n### Auto-detected follow-up

- Backend availability is **unknown** — confirm with human before implementing API-dependent behavior.
`;
  }

  fs.writeFileSync(p, content);
  markArtifactStatus(p, 'ready');
  return { path: p, availability, needsBackend };
}
